backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Exercicios
  - name: "exercicios" # Used in routes, e.g., /admin/collections/blog
    label: "Exercicios" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Sumario"
        name: "summary"
        widget: "text"

      - label: "Etiquetas"
        name: "tags"
        widget: "list"
        default: ["post"]

      - label: "Ocultar"
        name: "eleventyExcludeFromCollections"
        widget: "boolean"
        default: false
        required: false

      - label: "Corpo"
        name: "body"
        widget: "markdown"
  # Páxinas
  - name: "paxinas"
    label: "Páxinas"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      
      - label: "Filtro"
        name: "filter"
        widget: "string"
        required: false
      
      - label: "Plantilla"
        name: "layout"
        widget: "string"
        default: layouts/exercicios.njk

      - label: "Corpo"
        name: "body"
        widget: "markdown"
